name: Debug Trigger

on:
  push:

  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Print Event
        run: |
          echo "Workflow triggered!"
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "actor=${{ github.actor }}"
